### ISSUE TITLE
Plugin Icon Still Incorrect

### ISSUE THREAD

**Issue by SainteCelery** [jwsolve/HDMoviesDownload.bundle#1]
The channel icon is still showing as OnlineMoviesPro because the file icon-default.png in Contents/Services/Resources/ is for OnlineMoviesPro, not HDMoviesDownload. There is, additionally, an extra icon named onlinemoviespro-icon.png

**Comment by jwsolve** [comment]
I've removed the icon and the services resource folder,  if it still shows now then it's just a cache thing with the browser
